"""Tablo içeriği

Revision ID: 29c611500192
Revises: c1d8e19bf109
Create Date: 2026-04-28 21:08:50.009264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c611500192'
down_revision: Union[str, Sequence[str], None] = 'c1d8e19bf109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'last_active_date')
    # ### end Alembic commands ###
