"""boss_savasi_ve_oyunlastirma_eklendi

Revision ID: 30165e5e2a5a
Revises: 83b89d77fd71
Create Date: 2026-04-19 18:47:08.366980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30165e5e2a5a'
down_revision: Union[str, Sequence[str], None] = '83b89d77fd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'target_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'target_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
