"""Added last_roleplay_date

Revision ID: 4557f868c123
Revises: 29c611500192
Create Date: 2026-05-01 16:00:00.835181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4557f868c123'
down_revision: Union[str, Sequence[str], None] = '29c611500192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('last_roleplay_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'last_roleplay_date')
    # ### end Alembic commands ###
