"""added_lives_and_heart_timer

Revision ID: 5332ff2549fe
Revises: e806bc499219
Create Date: 2026-04-05 22:21:09.166973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5332ff2549fe'
down_revision: Union[str, Sequence[str], None] = 'e806bc499219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('lives', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('last_heart_lost', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'last_heart_lost')
    op.drop_column('user_progress', 'lives')
    # ### end Alembic commands ###
