"""added_pronunciation_texts_table

Revision ID: 57f1cf7d4a42
Revises: 30165e5e2a5a
Create Date: 2026-04-24 23:58:31.737280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f1cf7d4a42'
down_revision: Union[str, Sequence[str], None] = '30165e5e2a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_texts_id'), 'pronunciation_texts', ['id'], unique=False)
    op.create_index(op.f('ix_pronunciation_texts_level'), 'pronunciation_texts', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_texts_level'), table_name='pronunciation_texts')
    op.drop_index(op.f('ix_pronunciation_texts_id'), table_name='pronunciation_texts')
    op.drop_table('pronunciation_texts')
    # ### end Alembic commands ###
