"""added_target_words_to_lessons

Revision ID: 877cf150f8c3
Revises: e39e94746699
Create Date: 2026-04-04 23:12:46.083740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877cf150f8c3'
down_revision: Union[str, Sequence[str], None] = 'e39e94746699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('target_words', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'target_words')
    # ### end Alembic commands ###
