"""coklu_dil_destegi_eklendi

Revision ID: b32594efc85c
Revises: e3be0d656d0a
Create Date: 2026-04-04 17:35:29.744099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32594efc85c'
down_revision: Union[str, Sequence[str], None] = 'e3be0d656d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('current_section', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('current_lesson', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('level_completion_percentage', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_user_language', 'user_progress', ['user_id', 'target_language'])
    op.drop_column('users', 'current_section')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'current_lesson')
    op.drop_column('users', 'level_completion_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level_completion_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_lesson', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_section', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_user_language', 'user_progress', type_='unique')
    op.drop_column('user_progress', 'level_completion_percentage')
    op.drop_column('user_progress', 'streak_days')
    op.drop_column('user_progress', 'current_lesson')
    op.drop_column('user_progress', 'current_section')
    # ### end Alembic commands ###
