"""Yeni kolon eklendi

Revision ID: e09c0e96d603
Revises: b2bf993d0a3f
Create Date: 2026-05-06 11:12:10.524094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09c0e96d603'
down_revision: Union[str, Sequence[str], None] = 'b2bf993d0a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('target_language', sa.String(), nullable=True))
    op.create_index(op.f('ix_lessons_target_language'), 'lessons', ['target_language'], unique=False)
    op.add_column('pronunciation_texts', sa.Column('target_language', sa.String(), nullable=True))
    op.create_index(op.f('ix_pronunciation_texts_target_language'), 'pronunciation_texts', ['target_language'], unique=False)
    op.add_column('user_vocabulary', sa.Column('target_language', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_vocabulary_target_language'), 'user_vocabulary', ['target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vocabulary_target_language'), table_name='user_vocabulary')
    op.drop_column('user_vocabulary', 'target_language')
    op.drop_index(op.f('ix_pronunciation_texts_target_language'), table_name='pronunciation_texts')
    op.drop_column('pronunciation_texts', 'target_language')
    op.drop_index(op.f('ix_lessons_target_language'), table_name='lessons')
    op.drop_column('lessons', 'target_language')
    # ### end Alembic commands ###
