"""add_gamification_to_user_progress

Revision ID: e3be0d656d0a
Revises: c97f5966b640
Create Date: 2026-04-04 17:22:51.767262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3be0d656d0a'
down_revision: Union[str, Sequence[str], None] = 'c97f5966b640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_section', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_lesson', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level_completion_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level_completion_percentage')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'current_lesson')
    op.drop_column('users', 'current_section')
    # ### end Alembic commands ###
