"""add lang to mistakes

Revision ID: ee9a679e5199
Revises: e09c0e96d603
Create Date: 2026-05-07 20:02:27.548320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9a679e5199'
down_revision: Union[str, Sequence[str], None] = 'e09c0e96d603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('target_language', sa.String(), nullable=True))
    op.create_index(op.f('ix_mistakes_target_language'), 'mistakes', ['target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistakes_target_language'), table_name='mistakes')
    op.drop_column('mistakes', 'target_language')
    # ### end Alembic commands ###
